server:
  port: 9101
logging:
  level:
    root: INFO
    org:
      apache:
        zookeeper: warn
        hadoop: warn
  file: log/data-hbase.log

hbase:
  zookeeper:
    #    quorum: cldev-701-02,cldev-701-05,cldev-701-09
    quorum: 192.168.2.42,192.168.2.45,192.168.2.49
    property:
      clientPort: 2181
  table-name:
    #    mblog: mblog_from_uid
    pesg: mblog_from_uid_merge_pesg3
#    pesg: mblog_from_uid_pesg_test
#    mblog: uid_mid_blog_test3
    mblog: uid_mid_blog_hbase
zookeeper:
  znode:
    parent: /hbase-unsecure

datasource:
  weibo:
    url: jdbc:mysql://192.168.2.14:3308/clean_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: cldev
    max-active: 50
  weibo-marketing:
#    url: jdbc:mysql://192.168.2.14:3308/weibo_marketing?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: cldev
#    max-active: 50
    url: jdbc:mysql://192.168.2.16:3306/weibo_marketing?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    max-active: 50
