server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://192.168.2.15:3306/zhihu?useUnicode=true&characterEncoding=UTF-8
    username: sjx
    password: 123456
  redis:
    host: 192.168.56.128
    port: 6379
    password: 123456
logging:
  level:
    root: INFO
    com.cl.data.process: INFO
mybatis:
  type-aliases-package: com.cl.data.process.zhihu.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
